const {test}=require('node:test'),assert=require('node:assert/strict');
const {io}=require('socket.io-client'),{createApp}=require('../server');
const {QUESTIONS,KEYS,GROUP_LABELS}=require('../public/content');
const {KEY_ANSWERS,WHO_ANSWERS,EVIDENCE}=require('../curriculum');
const LESSON=require('../public/lesson-content'),RULES=require('../lesson-rules');

test('guest practice preserves personal work and published-only answers without changing class submissions, accuracy, feedback, votes or exports',async t=>{
  const app=createApp(),clients=[];
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
  t.after(async()=>{clients.forEach(c=>c.disconnect());await new Promise(r=>app.io.close(r));});
  const connect=async()=>{const c=io('http://127.0.0.1:'+app.server.address().port,{transports:['websocket'],forceNew:true});clients.push(c);await new Promise(r=>c.once('connect',r));return c;};
  const send=(c,e,p={})=>new Promise((resolve,reject)=>c.timeout(3000).emit(e,p,(err,x)=>err?reject(err):resolve(x)));
  const ok=async(c,e,p={})=>{const x=await send(c,e,p);assert.equal(x.ok,true,e+': '+x.error);return x;};
  const teacher=await connect(),joined=await ok(teacher,'teacher:join',{code:'PRACTICE',expected:GROUP_LABELS.length}),auth={code:'PRACTICE',token:joined.token};
  let state=joined.state;
  const actual=await connect(),actual2=await connect(),a=await connect(),b=await connect(),readonly=await connect();
  const realId={code:'PRACTICE',name:'Real student',group:1,clientId:'practice-real-1'};
  await ok(actual,'student:join',realId);
  await ok(actual2,'student:join',{code:'PRACTICE',name:'Second student',group:2,clientId:'practice-real-2'});
  const aId={code:'PRACTICE',name:'Guest A',group:1,clientId:'practice-guest-a',practice:true};
  const bId={code:'PRACTICE',name:'Guest B',group:1,clientId:'practice-guest-b',practice:true};
  assert.equal((await ok(a,'observer:join',aId)).practice,true);
  await ok(b,'observer:join',bId);
  await ok(readonly,'observer:join',{code:'PRACTICE',group:1,clientId:'practice-readonly'});
  const peek=async()=>state=(await ok(teacher,'teacher:join',auth)).state;
  const current=()=>({stage:state.stage,round:state.round});
  const guest=(c,e,p={})=>ok(c,e,{...current(),...p});
  const next=async()=>{await ok(teacher,'teacher:next',{...auth,...current()});await peek();};
  const reveal=async()=>{await ok(teacher,'teacher:reveal',{...auth,...current()});await peek();};
  const unchanged=async before=>assert.deepEqual(await peek(),before);
  await peek();assert.equal(state.joined,2);assert.equal(state.connected,2);assert.equal(state.observers,3);
  assert.equal((await send(readonly,'lesson:draft',{...current(),answer:[0]})).ok,false);
  let before=structuredClone(state);
  await guest(a,'lesson:draft',{answer:[1]});await guest(a,'lesson:submit');await unchanged(before);
  assert.equal((await ok(b,'observer:join',bId)).personal.lessonDraft,null);
  assert.equal((await ok(a,'observer:join',aId)).personal.practiceResult,null);
  await next();assert.equal(state.stage,'vocabMatch');
  before=structuredClone(state);
  await guest(a,'lesson:draft',{answer:RULES.vocabMatch});await guest(a,'lesson:submit');await unchanged(before);
  assert.equal((await ok(a,'observer:join',aId)).personal.practiceResult,null);
  await reveal();assert.deepEqual((await ok(a,'observer:join',aId)).personal.practiceResult.correct,Array(LESSON.vocabMatch.questions.length).fill(true));
  assert.equal(state.submitted,0);assert.ok(state.lessonRows.every(r=>r.answer===null));
  while(state.stage!=='keys')await next();
  const phrase=QUESTIONS[0].slice(0,8);
  await guest(actual,'group:mark',{q:0,start:0,end:phrase.length,selected:true});
  await guest(actual,'group:draft',{q:0,field:'key',value:KEY_ANSWERS[1]});
  const actualBefore=(await ok(actual,'student:join',realId)).personal;
  before=structuredClone(await peek());
  for(let q=0;q<GROUP_LABELS.length;q++){
    await guest(a,'group:mark',{q,start:0,end:8,selected:true});
    await guest(a,'group:draft',{q,field:'key',value:KEY_ANSWERS[q]});
  }
  await guest(a,'group:submit');await unchanged(before);
  assert.deepEqual((await ok(actual,'student:join',realId)).personal,actualBefore);
  assert.ok((await ok(b,'observer:join',bId)).personal.draft.every(v=>v===null));
  await next();await next();assert.equal(state.stage,'combined');
  await guest(actual,'group:draft',{field:'who',value:WHO_ANSWERS[1]});
  await guest(actual,'group:draft',{field:'evidence',value:EVIDENCE[1][0]});
  before=structuredClone(await peek());
  await guest(a,'group:draft',{field:'who',value:WHO_ANSWERS[0]});
  for(const id of EVIDENCE[0])await guest(a,'group:draft',{field:'evidence',value:id});
  await guest(a,'group:submit');await unchanged(before);
  assert.deepEqual((await ok(a,'observer:join',aId)).personal.answers,{who:WHO_ANSWERS[0],evidence:EVIDENCE[0]});
  assert.equal((await ok(b,'observer:join',bId)).personal.draft.who,null);
  assert.equal((await send(a,'student:record')).ok,false);
  await next();assert.equal(state.stage,'peer');before=structuredClone(state);
  await guest(a,'group:feedback',{status:'approved',note:'Only my practice feedback'});
  await guest(a,'group:submit');await unchanged(before);assert.equal(state.reviewed,0);
  await next();assert.equal(state.stage,'summary');await next();assert.equal(state.stage,'exit');before=structuredClone(state);
  const exit=LESSON.exit.questions.map(({q})=>({key:KEY_ANSWERS[q],who:WHO_ANSWERS[q],evidence:EVIDENCE[q]}));
  await guest(a,'lesson:draft',{answer:exit});await guest(a,'lesson:submit');await unchanged(before);
  assert.equal((await send(a,'student:record')).ok,false);
  await reveal();before=structuredClone(state);
  await guest(a,'student:notes',{notes:'Only Guest A sees this reflection.'});
  const own=(await ok(a,'student:record')).record;
  assert.equal(own.practice,true);assert.equal(own.name,'Guest A');assert.equal(own.notes,'Only Guest A sees this reflection.');
  assert.deepEqual(own.groups[0].initial,{who:WHO_ANSWERS[0],evidence:EVIDENCE[0]});
  assert.deepEqual(own.groups[0].exitGrade,exit.map(()=>true));assert.deepEqual(own.keys,KEYS);
  await unchanged(before);
  const all=(await ok(teacher,'teacher:record',auth)).record;
  assert.deepEqual(all.students.map(s=>s.name),['Real student','Second student']);
  assert.ok(!JSON.stringify(all).includes('Only Guest A'));assert.ok(!JSON.stringify(all).includes('My guest practice response'));
  assert.ok(all.groups.every(g=>g.lessonAnswers.exit===undefined));
  assert.equal((await ok(b,'student:record')).record.notes,'');
  await ok(teacher,'teacher:reset',{...auth,...current()});await peek();assert.equal(state.round,2);
  const reset=(await ok(a,'observer:join',aId)).personal;assert.equal(reset.notes,'');assert.equal(reset.lessonAnswer,null);
});

test('late guest joins and practice-group switching start with independent drafts while legacy viewers remain read-only',async t=>{
  const app=createApp(),clients=[];await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
  t.after(async()=>{clients.forEach(c=>c.disconnect());await new Promise(r=>app.io.close(r));});
  const connect=async()=>{const c=io('http://127.0.0.1:'+app.server.address().port,{transports:['websocket'],forceNew:true});clients.push(c);await new Promise(r=>c.once('connect',r));return c;};
  const send=(c,e,p={})=>new Promise((r,j)=>c.timeout(3000).emit(e,p,(err,x)=>err?j(err):r(x)));
  const teacher=await connect(),r=await send(teacher,'teacher:join',{code:'LATEPRACT'}),auth={code:'LATEPRACT',token:r.token};let state=r.state;
  while(state.stage!=='peer'){await send(teacher,'teacher:next',{...auth,stage:state.stage,round:1});state=(await send(teacher,'teacher:join',auth)).state;}
  const a=await connect(),identity={code:'LATEPRACT',clientId:'late-practice-guest',group:1,practice:true};
  let p=(await send(a,'observer:join',identity)).personal;assert.equal(p.eligible,true);
  await send(a,'group:draft',{stage:'peer',round:1,field:'who',value:WHO_ANSWERS[0]});
  p=(await send(a,'observer:group',{group:2})).personal;assert.equal(p.group,2);assert.equal(p.draft.who,null);
  p=(await send(a,'observer:group',{group:1})).personal;assert.equal(p.draft.who,WHO_ANSWERS[0]);
  state=(await send(teacher,'teacher:join',auth)).state;assert.equal(state.joined,0);assert.equal(state.submitted,0);assert.equal(state.reviewed,0);
});
