const {test}=require('node:test'),assert=require('node:assert/strict');
const {io}=require('socket.io-client'),{createApp}=require('../server');
const {KEY_ANSWERS,WHO_ANSWERS,EVIDENCE}=require('../curriculum');
const {findByName}=require('../participant-resume');
test('closing a page then joining by the same name restores the original group and work at the current stage, including after exit reveal, without adding a student',async t=>{
  const app=createApp(),clients=[];await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
  t.after(async()=>{clients.forEach(c=>c.disconnect());await new Promise(r=>app.io.close(r));});
  const connect=async()=>{const c=io('http://127.0.0.1:'+app.server.address().port,{transports:['websocket'],forceNew:true});clients.push(c);await new Promise(r=>c.once('connect',r));return c;};
  const send=(c,e,p={})=>new Promise((r,j)=>c.timeout(3000).emit(e,p,(err,x)=>err?j(err):x.ok?r(x):j(Error(e+': '+x.error))));
  const teacher=await connect(),j=await send(teacher,'teacher:join',{code:'NAMERETURN'}),auth={code:'NAMERETURN',token:j.token};assert.equal(j.created,true);let s=j.state;
  const peek=async()=>{const r=await send(teacher,'teacher:join',auth);assert.equal(r.created,false);return s=r.state;};
  const current=()=>({stage:s.stage,round:s.round});
  const next=async()=>{await send(teacher,'teacher:next',{...auth,...current()});await peek();};
  const first=await connect();let r=await send(first,'student:join',{code:'NAMERETURN',clientId:'name-first-browser',name:'Amy Stone',group:2});assert.equal(r.resumed,false);
  while(s.stage!=='keys')await next();
  await send(first,'group:draft',{...current(),q:1,field:'key',value:KEY_ANSWERS[1]});
  await send(first,'group:mark',{...current(),q:1,start:0,end:8,selected:true});
  first.disconnect();await next();await next();assert.equal(s.stage,'combined');
  const reopened=await connect();r=await send(reopened,'student:join',{code:'NAMERETURN',clientId:'name-fresh-browser',name:'  AMY   STONE  ',group:1});
  assert.equal(r.resumed,true);assert.equal(r.name,'Amy Stone');assert.equal(r.group,2);assert.equal(r.personal.stage,'combined');assert.equal(r.personal.keyMarkings[1][0].end,8);
  assert.equal(r.state.joined,1);assert.equal(r.state.connected,1);assert.deepEqual(r.state.groups[1].members.map(m=>m.name),['Amy Stone']);
  await send(reopened,'group:draft',{...current(),field:'who',value:WHO_ANSWERS[1]});
  await send(reopened,'group:draft',{...current(),field:'evidence',value:EVIDENCE[1][0]});
  reopened.disconnect();await next();assert.equal(s.stage,'peer');
  const peer=await connect();r=await send(peer,'student:join',{code:'NAMERETURN',clientId:'name-third-browser',name:'Amy Stone',group:1});
  assert.equal(r.group,2);assert.equal(r.personal.originalTimedOut,true);assert.equal(r.personal.original.who,WHO_ANSWERS[1]);assert.deepEqual(r.personal.original.evidence,[EVIDENCE[1][0]]);
  while(s.stage!=='exit')await next();
  await send(peer,'student:notes',{...current(),notes:'My personal reflection survives closing the page.'});
  peer.disconnect();await send(teacher,'teacher:reveal',{...auth,...current()});await peek();
  const final=await connect();r=await send(final,'student:join',{code:'NAMERETURN',clientId:'name-final-browser',name:'Amy Stone',group:1});
  assert.equal(r.resumed,true);assert.equal(r.personal.notes,'My personal reflection survives closing the page.');assert.equal(r.personal.notesRevision,1);
  assert.equal(r.state.joined,1);assert.equal((await send(final,'student:record')).record.group,2);
  const otherTeacher=await connect(),different=await send(otherTeacher,'teacher:join',{code:'ANOTHERROOM'});
  const other=await connect();r=await send(other,'student:join',{code:'ANOTHERROOM',clientId:'name-other-room',name:'Amy Stone',group:1});assert.equal(r.resumed,false);assert.equal(r.personal.notes,'');assert.equal(r.group,1);assert.equal(different.created,true);
});
test('named guest return restores only their independent practice and never resumes a formal student of the same name',async t=>{
  const app=createApp(),clients=[];await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
  t.after(async()=>{clients.forEach(c=>c.disconnect());await new Promise(r=>app.io.close(r));});
  const connect=async()=>{const c=io('http://127.0.0.1:'+app.server.address().port,{transports:['websocket'],forceNew:true});clients.push(c);await new Promise(r=>c.once('connect',r));return c;};
  const send=(c,e,p={})=>new Promise((r,j)=>c.timeout(3000).emit(e,p,(err,x)=>err?j(err):x.ok?r(x):j(Error(e+': '+x.error))));
  const teacher=await connect(),j=await send(teacher,'teacher:join',{code:'GUESTNAME'}),auth={code:'GUESTNAME',token:j.token};let state=j.state;
  const real=await connect();await send(real,'student:join',{code:'GUESTNAME',clientId:'guestname-real-id',name:'Robin',group:1});
  const guest=await connect();await send(guest,'observer:join',{code:'GUESTNAME',clientId:'guestname-original-id',name:'Robin',group:2,practice:true});
  await send(guest,'lesson:draft',{stage:'lead',round:1,answer:[1]});await send(guest,'lesson:submit',{stage:'lead',round:1});guest.disconnect();
  const reopened=await connect();let r=await send(reopened,'observer:join',{code:'GUESTNAME',clientId:'guestname-new-browser',name:'Robin',group:1,practice:true});
  assert.equal(r.resumed,true);assert.equal(r.group,2);assert.deepEqual(r.personal.lessonAnswer,[1]);assert.equal(r.state.submitted,0);assert.equal(r.state.joined,1);
  assert.equal((await send(real,'student:join',{code:'GUESTNAME',clientId:'guestname-real-id',name:'Robin',group:1})).personal.lessonAnswer,null);
  state=(await send(teacher,'teacher:join',auth)).state;assert.equal(state.observers,1);
});
test('legacy repeated names use the original group to disambiguate; blank names never match',()=>{
  const map=new Map([['1',{name:'Alex',group:1}],['2',{name:'Alex',group:2}]]);
  assert.equal(findByName(map,'alex',2).group,2);assert.throws(()=>findByName(map,'Alex',3));assert.equal(findByName(map,'',1),null);
});
