const {test}=require('node:test'),assert=require('node:assert/strict'),{io}=require('socket.io-client'),{createApp}=require('../server');
test('students, legacy viewers and practice guests wait for authenticated START CLASS; refresh does not close an active class',async t=>{
const app=createApp(),clients=[];await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(async()=>{clients.forEach(c=>c.disconnect());await new Promise(r=>app.io.close(r));});
const connect=async()=>{const c=io('http://127.0.0.1:'+app.server.address().port,{transports:['websocket'],forceNew:true});clients.push(c);await new Promise(r=>c.once('connect',r));return c;},send=(c,e,p={})=>new Promise((r,j)=>c.timeout(3000).emit(e,p,(err,x)=>err?j(err):x.ok?r(x):j(Error(x.error))));
const teacher=await connect(),joined=await send(teacher,'teacher:join',{code:'STARTGATE'}),auth={code:'STARTGATE',token:joined.token};assert.equal(joined.state.classStarted,false);
const student=await connect(),guest=await connect(),viewer=await connect();const identity={code:'STARTGATE',name:'Amy',group:1,clientId:'startgate-real-member'},guestId={code:'STARTGATE',name:'Practice',group:2,clientId:'startgate-practice-user',practice:true};
for(const [c,event,p] of [[student,'student:join',identity],[guest,'observer:join',guestId],[viewer,'observer:join',{code:'STARTGATE',group:1,clientId:'startgate-legacy-viewer'}]]){const r=await send(c,event,p);assert.equal(r.state.classStarted,false);assert.equal(r.personal.target,undefined);assert.equal(r.personal.draft,undefined);}
const current={stage:'lead',round:1};await assert.rejects(send(student,'lesson:draft',{...current,answer:[0]}),/START CLASS/);await assert.rejects(send(guest,'lesson:draft',{...current,answer:[1]}),/START CLASS/);await assert.rejects(send(student,'teacher:start',auth));await assert.rejects(send(guest,'teacher:start',auth));await assert.rejects(send(teacher,'teacher:next',{...auth,...current}),/START CLASS/);
const started=await send(teacher,'teacher:start',auth);assert.equal(started.state.classStarted,true);assert.equal(started.state.stage,'lead');assert.equal((await send(student,'student:join',identity)).personal.lessonDraft,null);await send(student,'lesson:draft',{...current,answer:[0]});await send(student,'lesson:submit',current);await send(guest,'lesson:draft',{...current,answer:[1]});await send(guest,'lesson:submit',current);
assert.equal((await send(teacher,'teacher:join',auth)).state.submitted,1);assert.equal((await send(teacher,'teacher:join',auth)).state.classStarted,true);assert.deepEqual((await send(student,'student:join',identity)).personal.lessonAnswer,[0]);assert.equal((await send(viewer,'observer:join',{code:'STARTGATE',group:1,clientId:'startgate-legacy-viewer'})).state.classStarted,true);
});
